config/routes.rb
Radd::Application.routes.draw do
  get '/auth/:provider/callback', to: 'home#create'

  
 

  resources :home, only: [:index]
  root :to => "home#index"
  devise_for :users

=begin
  resource :facebook, :except => :create do
    get :callback, action: :create
  end
  
  resource :facebooks, :only=>:index do
    collection do
      get 'index'
    end
  end

  resource :twitter, :except => :create do
    get :callback, action: :create
  end
  resource :twitters, :only=>:index do
    collection do
      get 'index'
    end
  end
=end

  namespace :api, defaults: {format: :json} do
    scope module: :v2, constraints: ApiConstraints.new(version: 1, default: :true) do

      devise_scope :user do
        match '/sessions' => 'sessions#create', :via => :post
        match '/sessions' => 'sessions#destroy', :via => :delete
      end

      match '/reports' => "reports#index", via: [:get,:post]
      
      resources :record do
        collection do
          get 'roles'
        end
      end

      resources :accounts do
        collection do
          get 'countries'
          get 'users'
          get 'lookups'
          get 'segments'
        end
      end
      resources :organizations
      resources :groups
      resources :subgroups
      resources :regions
      resources :countries
      resources :sc_segments, :path => "segments"
      resources :languages
      resources :media_types
      resources :accounts_countries
      resources :accounts_sc_segments, :path => "accounts_segments"
      resources :accounts_regions
      resources :accounts_users
      resources :accounts_groups
      resources :accounts_subgroups
      resources :subroles  # , :only=>:index
      resources :users do
        get 'timeout'
        collection do
          get 'roles'
          get 'confirm'
          get 'forget_password'
          get 'reset_password'
          post 'reset_password'
        end
      end

      match '/show_all_accounts' => 'accounts#show_all', :via => :get
      

    end
  end

  namespace :admin do
    resources :error_logs do
      as_routes
      collection do
        get 'fetch'
      end
    end
=begin 
    3/18/15 
    resources :fb_pages do
      as_routes
    end
    resources :tw_timelines do
      as_routes
    end
    resources :accounts,:facebook_accounts,:twitter_accounts do
      as_routes
      collection do
        match '/insights/*path' => "accounts#insights", via: [:get]
        get 'start_producers'
        get 'stop_producers'
        get 'start_consumer'
        get 'stop_consumer'
        get 'fetch'
      end
    end
    resources :groups do
      as_routes
    end
    
    resources :subgroups do
      as_routes
    end
    
    resources :regions do
      as_routes
    end
    
    resources :countries do
      as_routes
    end
    resources :sc_segments do
      as_routes
    end
    resources :languages do
      as_routes
    end
    
    resources :accounts_countries do
      as_routes
    end
    resources :accounts_sc_segments do
      as_routes
    end
    resources :accounts_regions do
      as_routes
    end
    resources :accounts_users do
      as_routes
    end
=end    
    resources :users do
      as_routes
      member do
        get 'ed'
      end
      
      collection do
        get 'ls'
      end
    end
  end

end

app/models/facebook.rb
class Facebook < ActiveRecord::Base
  has_many :subscriptions

  cattr_accessor :app_token
  
  def profile
    @profile ||= FbGraph::User.me(self.access_token).fetch
  end

  class << self
    def not_empty? text
      !!text && !text.strip.empty?
    end
    
    def config(env=Rails.env)
      @config = 
        cnf = YAML.load_file("#{Rails.root}/config/facebook.yml")[env].symbolize_keys
        # add email, client_id, client_secret, canvas_url to Accounts table
        if app_token
           client_id=app_token.client_id if not_empty?(app_token.client_id) 
           client_secret=app_token.client_secret if not_empty?(app_token.client_secret)
           canvas_url = app_token.canvas_url || 'ads.localhost.com'
           cnf = {:client_id=>client_id,
                  :client_secret=>client_secret,
                  :scope=> cnf[:scope],
                  :canvas_url=>canvas_url}
        end
        cnf
    rescue Errno::ENOENT => e
      raise StandardError.new("config/facebook.yml could not be loaded.")
    end

    def app
      FbGraph::Application.new config[:client_id], :secret => config[:client_secret]
    end

    def auth(redirect_uri = nil)
      FbGraph::Auth.new config[:client_id], config[:client_secret], :redirect_uri => redirect_uri
    end

    def identify(fb_user)
      _fb_user_ = find_or_initialize_by(identifier: fb_user.identifier.try(:to_s))
      _fb_user_.access_token = fb_user.access_token.access_token
      _fb_user_.save!
      _fb_user_
    end
  end

end

app/views/facebooks/_account.html.erb
 <h3>This App can get full Insights for the following Facebook pages
  which have access token</h3>
  <span><b>User</b> : <%= @user %></span>&nbsp;&nbsp;&nbsp;&nbsp;
 
  <span><b>AccessToken Count</b> : <%= @token_count %></span>
  <table border="1">
<tr>
  <th class="alabel1"><b>ID</b></th>
  <th class="alabel1"><b>Object Name</b></th>
  <th class="alabel2"><b>Updated</b></th>
  <th class="alabel2"><b>Access Token?</b></th>
  <th class="alabel1"><b>Expire</b></th>
</tr>
<% @accounts.each do |a| %>
<tr>
  <td class="alabel1"><%= a.id %></td>
  <td class="alabel1"><%= a.object_name %></td>
  <td class="alabel2"><%= a.updated_at.to_s(:db) %></td>
  <td class="alabel1"><%= a.token? ? 'Yes' : 'No' %></td>
  <td class="alabel1"><%#= a.debug_token %></td>

</tr>
<% end %>
</table>

app/views/facebooks/index.html.erb
<style>
.content1 {margin: 10px auto; width: 900px; }
.float-left1 {float: left; width: 250px; }
.divide {float: left;width: 20px;}
.float-left2 {float: left; width: 600px; }
.label1 {display: inline-block; float:left;width: 200px; }
.label2 {display: inline-block; float:left;width: 200px; }
.twitter {clear: both;width: 1px; height: 40px;}
</style>
<script>
$( document ).ready(function() {
  $('#account_email').change(function () {
    var email = this.value;
    var url="<%= edit_facebook_path %>"
    $.get(url, {email: email}, function(data) {
      $('#accounts').html(data);
    });
  });
});  
</script>

<div class="content1">
<h1><%= "Facebook Authorization" %></h1>
<i>Environment: <%= Rails.env.to_s %></i>
<p>Create Facebook Account(s), if you want them to access InSights data,
in accounts table with column 'contact'
set to the app_user_email as in app_tokens table, see below:</p>
<p>
Create entries in app_tokens table with attributes:
<ul>
 
<li>platform: 'Facebook'</li>
<li>app_user_email: the email used to create a Facebook Application
</li>
<li>canvas_url: the domain name for convas_url in Facebook Application, eg. sm.bbg.gov
</li>  
<li>client_id: Facebook App client_id</li>
<li>client_secret: Facebook App client_secret</li>
</ul>
</p>

<p>This tool is for getting page access token for Facebook pages if the selected
  user (email) has "Page Role" for that page.
</p>
<p>The related Facebook Account(s), linked by 'contact' column, then has access to InSights data.
</p> 
<p>Currently, there are three users, each should have Page Role for various pages</p>
<ul>
<li>ads@bbg.gov</li>
<li>odditech@bbg.gov</li>
<li>oddidev@bbg.gov</li>
</ul>
<p>To get page access tokens
<ul>
<li>Login to facebook.com using the email with which a Facebook App is created
</li>
<li>If the Facebook App's Canvas_url is http://ads.localhost.com:3000/ <br />
  Goto page http://ads.localhost.com:3000/facebooks/index.
  *You need to add to /etc/hosts file with "127.0.0.1 ads.localhost.com"</li>

<li>If the Facebook App's Canvas_url is https://smdata.bbg.gov/ <br />
  Goto page https://smdata.bbg.gov/facebooks/index</li>

<li>In the Email dropdown list, select an email, e.g. ads@bbg.gov</li>
<li>Click Submit</li>
</ul>
After the process completed, the "Access Toten?" column in the table below will change to Yes
for all the pages the user has "Page Role"
</p>

<div class="float-left1">
<% if authenticated? %>
  <p><%= link_to "Logout", facebook_path, :method => :delete %></p>
<% elsif @account %>
  <% content_for :head do %>
  <%= stylesheet_link_tag 'projects' %>
  <% end %>

  <dl>
    <dt>JavaScript SDK</dt>
    <dd><fb:login-button length="long" onlogin="location.href = '<%= facebook_path %>'" scope="<%= Facebook.config[:scope] %>"></fb:login-button></dd>
    <dt>Normal OAuth flow</dt>
    <dd><%= link_to "Start", new_facebook_path %></dd>
  </dl>
<% end %>

<h2>Facebook Access Token</h2>
  <%    
     emails=options_for_select(@emails)
  %>
  <%= form_tag(new_facebook_path, :method=>'get') do %>
  <%= select_tag('account[email]', emails,:multiple => false,:readonly=>true) %>
  <%= submit_tag "Submit" %>
  <% end %>

</div>
<div class="divide">&nbsp;</div>
<div id="accounts" class="float-left2">
    <%#= render :partial=>'account' %>
</div>
<div class="twitter">&nbsp;</div>